### ISSUE TITLE
Error in location parser

### ISSUE THREAD

**Issue by realfinklej** [raleighlittles/Snapchat-Chats-And-Location-Analyzer#2]
Trying to use the map feature but get this error

`Traceback (most recent call last):
  File "C:\Users\Daniel\Downloads\Snapchat-Chats-And-Location-Analyzer-main\Snapchat-Chats-And-Location-Analyzer-main\snapchat_location_history_analyzer.py", line 36, in <module>
    generate_folium_map(argparse_args.input_file, argparse_args.output_file)
  File "C:\Users\Daniel\Downloads\Snapchat-Chats-And-Location-Analyzer-main\Snapchat-Chats-And-Location-Analyzer-main\snapchat_location_history_analyzer.py", line 14, in generate_folium_map
    timestamps, latitudes, longitudes = location_parser_helper.get_location_history_coordinates(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\Downloads\Snapchat-Chats-And-Location-Analyzer-main\Snapchat-Chats-And-Location-Analyzer-main\location_parser_helper.py", line 18, in get_location_history_coordinates
    timestamps.append(entry['Time'])
                      ~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not `str``

**Comment by raleighlittles** [comment]
@realfinklej I'll create a data dump and look into this. Also in general:
* don't create an issue with a generic one-word title, put at least a little bit of information in the title
* Include what operating system and Python version you're using

**Comment by raleighlittles** [comment]
The format of the Location history files appear to have changed from the older dumps, I've fixed it so that hopefully it should work with both.

![image](https://github.com/user-attachments/assets/e58b5fc4-4fd6-4d77-99fc-53929da2a69e)
